# Fingerprint Tutorial 1

**Contributing Authors**  
Andrew Trepagnier,
*Mississippi State University*  
📧 andrew.trepagnier1@gmail.com

---

## Objective

To understand the process of training an interatomic potential, it is helpful to begin by demonstrating how structural fingerprints encode an atom’s local atomic environment as input to a neural network. This document is intended for anyone interested in training their own interatomic potential or learning more about the computational strategies used in Machine-Learned Interatomic Potentials (MLIPs).


## Introduction

Structural fingerprints are mathematical representations of an atom’s local atomic environment within a system of atoms or molecules. These fingerprints are crucial for converting high-dimensional data—such as the distances between atom i and atom j across hundreds of atoms and simulation timesteps—into lower-dimensional descriptors that still retain essential environmental information.

In this tutorial, I provide a step-by-step walkthrough for manually computing structural fingerprints, as seen in the referenced study. While the included fingerprint scripts can automatically parse input files and compute these descriptors efficiently, manually working through a basic example can help build intuition and strengthen understanding of how structural information is encoded.



<img src="fingerprintconversion.jpeg" alt="Diagram" width="500">

<div style="background-color:#f1f8e9; padding: 20px; border-left: 6px solid #7cb342; border-radius: 10px; font-size: 16px; line-height: 1.6">
    
## Priors

The priors listed below outline the two encoded fingerprint expressions and their associated variables for reference. The computation walkthrough will show how these are used practically.

### 🔷 Structural Fingerprint Expressions

- <b>Pair Interaction Definition</b>  
  $$
  F_{(n-o)} = \sum_{j \neq i} \left( \frac{r_{ij}}{r_e} \right)^{(n-o)} e^{-\alpha_n \frac{r_{ij}}{r_e}} f_c \left( \frac{r_c - r_{ij}}{\Delta r} \right) S_{ij}
  $$

- <b>3-Body Fingerprint</b>  
  $$
  \begin{split}
  G_{m,k} = \sum_{j,k} \cos^m \theta_{jik} \; & e^{-\beta_k \frac{r_{ij} + r_{ik}}{r_e}} 
  f_c \left( \frac{r_c - r_{ij}}{\Delta r} \right) \\
  & \times f_c \left( \frac{r_c - r_{ik}}{\Delta r} \right) 
  S_{ij} S_{ik}
  \end{split}
  $$


 <p> Where the Cutoff Function, $f_{c}$, is defined as</p>
    $$    
    f_c(x) =
    \begin{cases} 
    1, & x > 1 \\
    \left( 1 - (1 - x)^4 \right)^2, & 0 \leq x \leq 1 \\
    0, & x < 0
    \end{cases}
  $$

---

### 🔹 Pair-Interaction Variables

- \( n \): Integer that adjusts the number of fingerprints in the input layer  
- Euclidean distance between atom \( i \) and atom \( j \):  
  $$
  r_{ij} = \sqrt{(x_{j}-x_{i})^2 + (y_{j}-y_{i})^2 + (z_{j}-z_{i})^2}
  $$
- \( r_e \): Equilibrium distance between atoms  
- \( r_c \): Cutoff radius  
- \( \Delta r \): Difference in equilibrium radius and cutoff radius  
- \( \alpha_n \): The \( n \)th alpha in the vector of alphas, based on the bulk modulus of the material  

---

### 🔹 3-Body Variables

- \( m \): Integer  
- \( k \): Integer  
- \( \theta_{ijk} \): Interatomic angle between atom \( i \), atom \( j \), and atom \( k \)  
- Euclidean distance between atom \( i \) and atom \( j \):  
  $$
  r_{ij} = \sqrt{(x_{j}-x_{i})^2 + (y_{j}-y_{i})^2 + (z_{j}-z_{i})^2}
  $$
- \( r_e \): Equilibrium distance between atoms  
- \( r_c \): Cutoff radius  
- \( \Delta r \): Difference in equilibrium radius and cutoff radius  
- \( \beta_k \): Damping coefficient for distance penalty in 3-body term

</div>



## Step-by-Step Example

In [27]:
# Install Libraries
from dataclasses import dataclass
from typing import List, Optional, Dict
import numpy as np
import pandas as pd
import os

We consider a simple 2D system of 4 atoms arranged in a square configuration. We could imagine the coordinate locations would look something like this:
$$
\begin{aligned}
{atom}_0 &= (0, 0) \\
{atom}_1 &= (2, 0) \\
{atom}_2 &= (0, 2) \\
{atom}_3 &= (2, 2)
\end{aligned}
$$


In [28]:
atom0 = [0, 0]
atom1 = [2, 0]
atom2 = [0, 2]
atom3 = [2, 2]

atom_positions = np.stack((atom0, atom1, atom2, atom3))
print(atom_positions)

[[0 0]
 [2 0]
 [0 2]
 [2 2]]


Visually, the system of 4 atoms would look like:

<img src="box.jpeg" alt="Diagram" width="300">

Here, each colored node represents an atom in a 2D box. We consider pairwise distances and angles between atoms to compute a structural fingerprint vector for each atom.

### Distance Matrix

Next, we'll compute the distance matrix. For each ith atom that we consider, we want to calculate the euclidean distance between it and atom j, where atom j is each atom in the system (except i, itself, because that will always be zero). These are the ij distances. So for atom pair i=0 and j=1 (or also referred to as atom01), it would be computed as such:

$$ r_{01} = \sqrt{(2-0)^2 + (0-0)^2 } = 2$$

We need to do this for every pair of atoms, so let's make a nested for loop that would handle any nxm system of atom positions:


In [29]:
num_atoms = 4

distance_matrix = np.zeros([num_atoms, num_atoms])
for i in range(num_atoms):                                               
    for j in range(num_atoms):                                          
        if i != j:
            distance_matrix[i,j] = np.linalg.norm(atom_positions[i] - atom_positions[j])
print(distance_matrix)


[[0.         2.         2.         2.82842712]
 [2.         0.         2.82842712 2.        ]
 [2.         2.82842712 0.         2.        ]
 [2.82842712 2.         2.         0.        ]]


This can also be visualized as:

$$
\begin{array}{c|cccc}
        & \text{Atom}_0 & \text{Atom}_1 & \text{Atom}_2 & \text{Atom}_3 \\
\hline
\text{Atom}_0 & 0 & r_{01} & r_{02} & r_{03} \\
\text{Atom}_1 & r_{10} & 0 & r_{12} & r_{13} \\
\text{Atom}_2 & r_{20} & r_{21} & 0 & r_{23} \\
\text{Atom}_3 & r_{30} & r_{31} & r_{32} & 0 \\
\end{array}
$$

The size of the distance matrix grows exponentially with larger and larger systems(6x6 = 36 entries, 10x10= 100 entries, ...). Hence, why we must be strategic in how we compute the fingerprints with these values for systems of hundreds to thousands of atoms.


### Pair Interaction Fingerprint Computation


Here we will compute the pair interaction fingerprint. Below is an example of a list of metaparameters our input parsing function may extract:

> *Remember, these are not real values used in the study. They are to show how the fingerprint functions work.*

- `re = 1.1`
- `rc = 2.80`
- `αₙ = [6.95, 6.95, 6.95, 6.95]`
- `dr = 1.7`
- `o = -1`
- `n = 2`
- `n - o = 3`

According to our pair interaction fingerprint function, there will be **n - o** pair interaction fingerprints (array-based, so a total of **4**). Remember, our vector of fingerprints will be stacked together in a vector and act as the feature input like such:
Feature Input = 
$$
Feature Input = 
\begin{bmatrix}
F_{0} \\
F_{1} \\
F_{2} \\
F_{3} \\
F_{4} \\
G_{0,0}\\
. \\
. \\
.
\end{bmatrix}
$$





### Analytical interpretation of the Pair Interaction Fingerprints:

### For $F_{0}$:

<div style="background-color:#e0f7fa; padding: 15px; border-left: 5px solid #00796b; border-radius: 8px; margin-bottom: 10px;">
<b>Fingerprint Formula:</b><br>
$$
F_0 = \sum_{j \neq i} \left( \frac{r_{ij}}{r_e} \right)^0 \exp\left(-\alpha_0 \cdot \frac{r_{ij}}{r_e} \right) f_c\left( \frac{r_c - r_{ij}}{\Delta r} \right) S_{ij}
$$
</div>

<div style="display:flex; flex-direction:column; gap:10px;">

<!-- First term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 1 (j = 1):</b><br>
\( \left( \frac{r_{01}}{r_e} \right)^0 \cdot \exp\left(-\alpha_0 \cdot \frac{r_{01}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{01}}{\Delta r} \right) \cdot S_{01} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Second term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 2 (j = 2):</b><br>
\( \left( \frac{r_{02}}{r_e} \right)^0 \cdot \exp\left(-\alpha_0 \cdot \frac{r_{02}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{02}}{\Delta r} \right) \cdot S_{02} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Third term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 3 (j = 3):</b><br>
\( \left( \frac{r_{03}}{r_e} \right)^0 \cdot \exp\left(-\alpha_0 \cdot \frac{r_{03}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{03}}{\Delta r} \right) \cdot S_{03} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Ellipsis -->
<div style="text-align:center; font-size: 18px; color: #999;">
...and so on for all atoms \( j \ne i \)
</div>

</div>

---
### For $F_{1}$:

<div style="background-color:#e0f7fa; padding: 15px; border-left: 5px solid #00796b; border-radius: 8px; margin-bottom: 10px;">
<b>Fingerprint Formula:</b><br>
$$
F_1 = \sum_{j \neq i} \left( \frac{r_{ij}}{r_e} \right)^1 \exp\left(-\alpha_1 \cdot \frac{r_{ij}}{r_e} \right) f_c\left( \frac{r_c - r_{ij}}{\Delta r} \right) S_{ij}
$$
</div>

<div style="display:flex; flex-direction:column; gap:10px;">

<!-- First term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 1 (j = 1):</b><br>
\( \left( \frac{r_{01}}{r_e} \right)^1 \cdot \exp\left(-\alpha_1 \cdot \frac{r_{01}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{01}}{\Delta r} \right) \cdot S_{01} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Second term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 2 (j = 2):</b><br>
\( \left( \frac{r_{02}}{r_e} \right)^1 \cdot \exp\left(-\alpha_1 \cdot \frac{r_{02}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{02}}{\Delta r} \right) \cdot S_{02} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Third term -->
<div style="background-color:#fff3e0; padding: 10px; border-left: 5px solid #fb8c00; border-radius: 5px;">
<b>Term 3 (j = 3):</b><br>
\( \left( \frac{r_{03}}{r_e} \right)^1 \cdot \exp\left(-\alpha_1 \cdot \frac{r_{03}}{r_e} \right) \cdot f_c\left( \frac{r_c - r_{03}}{\Delta r} \right) \cdot S_{03} \)
</div>

<div style="text-align:center; font-size: 20px;">+</div>

<!-- Ellipsis -->
<div style="text-align:center; font-size: 18px; color: #999;">
...and so on for all atoms \( j \ne i \)
</div>

</div>


---
### Discussion

This would create n(array-based) pair interaction fingerprints($F_{0}$, $F_{1}, F_{2}, ...)$ that could be concantenated into an input feature vector. It is important to note at this point that each atom will recieve these sets of fingerprints. So, if your fingerprint vector is 29 entries, that would be 29 entries per atom in the system.

Notice that i = 0 remains the same in the computations above. The set of fingerprints above would be the feature input for atom i = 0, since it encodes atom i's distance relationship with all other j atoms in the system.

Before computing the fingerprints of the system of 4 atoms, we should make a lookup table of fingerprints first. A *Lookup Table* is a precomputed table of values that can be used along with interpolation techniques to find a value. This is done to enhance computational efficiency for the neural network. Instead of computing fingerprints for every atom 



In [32]:
class Fingerprint_lookup_table():
    
    def __init__(self, atom_positions, num_atoms):
        
        self.atom_positions = atom_positions
        self.num_atoms = num_atoms
        self.re = 1.1
        self.rc = 2.80
        self.alphan = [6.95, 6.95, 6.95, 6.95] #We consider a system of a pure element in this example so bulk modulus remains the same, alloys are different
        self.dr = 1.7
        self.o = -1
        self.n = 2
        self.m = self.n - self.o

    def cutoff(self, r) -> float:
        x = (self.rc - r) / self.dr
        if x > 1:
            return 1
        elif 0 <= x <= 1:
            return (1 - (1 - x)**4)**2 #Continuous cutoff range for smoother potentials
        else:
            return 0
        
    def radial_table(self) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        buffer = 5
        res = 1000
    
        radii_table = np.zeros((res + buffer, int(self.n - self.o)), dtype=float)  # (1005, n-o)
        dfctable = np.zeros(res + buffer)
        r1 = np.zeros(res + buffer)
    
        for m in range(self.m):
            """
            Consider m=0 first, compute PI fingerprints for all m=0 and save in the 0th column of radii_table,
            then increment and fill in next column until all m's are computed and stored
            """
            for k in range(res + buffer):
                r1[k] = self.rc * k / res
                r1_sqrt = np.sqrt(r1[k])
        
                term_of_mth_fp = (
                    (r1_sqrt / self.re) ** m *
                    np.exp(-self.alphan[m] * (r1_sqrt / self.re)) *
                    self.cutoff(r1_sqrt)
                )
                radii_table[k, m] = term_of_mth_fp
        
                if r1_sqrt >= self.rc or r1_sqrt <= self.rc - self.dr:
                    dfctable[k] = 0
                else:
                    term = (self.rc - r1_sqrt) / self.dr
                    dfctable[k] = (-8 * (1 - term) ** 3) / (self.dr * (1 - term) ** 4)
    
        return r1, radii_table, dfctable

if __name__ == '__main__':
    fp = Fingerprint_lookup_table(atom_positions, num_atoms)
    _, radii_table, _ = fp.radial_table()
    print(f"The radii_table: {radii_table}")
    print(f"The radii_table shape: {np.shape(radii_table)}")
    

The radii_table: [[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.15819845e-01 3.44342053e-02 1.65644262e-03]
 [6.23248830e-01 4.23997016e-02 2.88445740e-03]
 ...
 [2.46864766e-05 3.75906037e-05 5.72399825e-05]
 [2.45526919e-05 3.74055385e-05 5.69865950e-05]
 [2.44196816e-05 3.72214411e-05 5.67343875e-05]]
The radii_table shape: (1005, 3)
